name: Eka testi
favicon: null
layout_spectrum: 0.88039
typography_spectrum: 0.28166
title: Eka title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5886a8'
    - '#1e1822'
    - '#ede5e3'
    - '#743130'
    - '#dc8f95'
  brandStrength: 0.125
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
